"use client"
import Navbar from "@/components/Navbar";
import "../styles/globals.css";
import Head from "next/head";
import type { Metadata } from "next";
import styles from "../styles/page.module.css";

export const metadata: Metadata = {
  title: "L'Innovation à travers le design web",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.background}>
        <Head>
          <link rel="icon" href="/favicon.png" />
        </Head>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
